(cl:defpackage marvelmind_nav-msg
  (:use )
  (:export
   "<MARVELMINDUSERDATA>"
   "MARVELMINDUSERDATA"
   "<BEACON_DISTANCE>"
   "BEACON_DISTANCE"
   "<BEACON_POS_A>"
   "BEACON_POS_A"
   "<HEDGE_IMU_FUSION>"
   "HEDGE_IMU_FUSION"
   "<HEDGE_IMU_RAW>"
   "HEDGE_IMU_RAW"
   "<HEDGE_POS>"
   "HEDGE_POS"
   "<HEDGE_POS_A>"
   "HEDGE_POS_A"
   "<HEDGE_POS_ANG>"
   "HEDGE_POS_ANG"
   "<HEDGE_QUALITY>"
   "HEDGE_QUALITY"
   "<HEDGE_TELEMETRY>"
   "HEDGE_TELEMETRY"
   "<MARVELMIND_WAYPOINT>"
   "MARVELMIND_WAYPOINT"
  ))

