(cl:defpackage service_tutorial-srv
  (:use )
  (:export
   "CONTROLTURNINGMESSAGE"
   "<CONTROLTURNINGMESSAGE-REQUEST>"
   "CONTROLTURNINGMESSAGE-REQUEST"
   "<CONTROLTURNINGMESSAGE-RESPONSE>"
   "CONTROLTURNINGMESSAGE-RESPONSE"
  ))

