// Generated by gencpp from file action_tutorial/MazeResult.msg
// DO NOT EDIT!


#ifndef ACTION_TUTORIAL_MESSAGE_MAZERESULT_H
#define ACTION_TUTORIAL_MESSAGE_MAZERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_tutorial
{
template <class ContainerAllocator>
struct MazeResult_
{
  typedef MazeResult_<ContainerAllocator> Type;

  MazeResult_()
    : success(false)  {
    }
  MazeResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::action_tutorial::MazeResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_tutorial::MazeResult_<ContainerAllocator> const> ConstPtr;

}; // struct MazeResult_

typedef ::action_tutorial::MazeResult_<std::allocator<void> > MazeResult;

typedef boost::shared_ptr< ::action_tutorial::MazeResult > MazeResultPtr;
typedef boost::shared_ptr< ::action_tutorial::MazeResult const> MazeResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_tutorial::MazeResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_tutorial::MazeResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_tutorial::MazeResult_<ContainerAllocator1> & lhs, const ::action_tutorial::MazeResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_tutorial::MazeResult_<ContainerAllocator1> & lhs, const ::action_tutorial::MazeResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_tutorial::MazeResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_tutorial::MazeResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_tutorial::MazeResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_tutorial::MazeResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_tutorial::MazeResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_tutorial::MazeResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_tutorial::MazeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::action_tutorial::MazeResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_tutorial::MazeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_tutorial/MazeResult";
  }

  static const char* value(const ::action_tutorial::MazeResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_tutorial::MazeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool success\n"
;
  }

  static const char* value(const ::action_tutorial::MazeResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_tutorial::MazeResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MazeResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_tutorial::MazeResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_tutorial::MazeResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_TUTORIAL_MESSAGE_MAZERESULT_H
