// Generated by gencpp from file action_tutorial/MazeFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_TUTORIAL_MESSAGE_MAZEFEEDBACK_H
#define ACTION_TUTORIAL_MESSAGE_MAZEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_tutorial
{
template <class ContainerAllocator>
struct MazeFeedback_
{
  typedef MazeFeedback_<ContainerAllocator> Type;

  MazeFeedback_()
    : feedback_msg()  {
    }
  MazeFeedback_(const ContainerAllocator& _alloc)
    : feedback_msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _feedback_msg_type;
  _feedback_msg_type feedback_msg;





  typedef boost::shared_ptr< ::action_tutorial::MazeFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_tutorial::MazeFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MazeFeedback_

typedef ::action_tutorial::MazeFeedback_<std::allocator<void> > MazeFeedback;

typedef boost::shared_ptr< ::action_tutorial::MazeFeedback > MazeFeedbackPtr;
typedef boost::shared_ptr< ::action_tutorial::MazeFeedback const> MazeFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_tutorial::MazeFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_tutorial::MazeFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_tutorial::MazeFeedback_<ContainerAllocator1> & lhs, const ::action_tutorial::MazeFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.feedback_msg == rhs.feedback_msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_tutorial::MazeFeedback_<ContainerAllocator1> & lhs, const ::action_tutorial::MazeFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_tutorial::MazeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_tutorial::MazeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_tutorial::MazeFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_tutorial::MazeFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_tutorial::MazeFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_tutorial::MazeFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_tutorial::MazeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2d0a7665728d7af4a27ddb9a948c8e6";
  }

  static const char* value(const ::action_tutorial::MazeFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2d0a7665728d7afULL;
  static const uint64_t static_value2 = 0x4a27ddb9a948c8e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_tutorial::MazeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_tutorial/MazeFeedback";
  }

  static const char* value(const ::action_tutorial::MazeFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_tutorial::MazeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string feedback_msg\n"
;
  }

  static const char* value(const ::action_tutorial::MazeFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_tutorial::MazeFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MazeFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_tutorial::MazeFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_tutorial::MazeFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.feedback_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_TUTORIAL_MESSAGE_MAZEFEEDBACK_H
