// Generated by gencpp from file marvelmind_nav/MarvelmindAPIRequest.msg
// DO NOT EDIT!


#ifndef MARVELMIND_NAV_MESSAGE_MARVELMINDAPIREQUEST_H
#define MARVELMIND_NAV_MESSAGE_MARVELMINDAPIREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marvelmind_nav
{
template <class ContainerAllocator>
struct MarvelmindAPIRequest_
{
  typedef MarvelmindAPIRequest_<ContainerAllocator> Type;

  MarvelmindAPIRequest_()
    : command_id(0)
    , request()  {
    }
  MarvelmindAPIRequest_(const ContainerAllocator& _alloc)
    : command_id(0)
    , request(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _command_id_type;
  _command_id_type command_id;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MarvelmindAPIRequest_

typedef ::marvelmind_nav::MarvelmindAPIRequest_<std::allocator<void> > MarvelmindAPIRequest;

typedef boost::shared_ptr< ::marvelmind_nav::MarvelmindAPIRequest > MarvelmindAPIRequestPtr;
typedef boost::shared_ptr< ::marvelmind_nav::MarvelmindAPIRequest const> MarvelmindAPIRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator1> & lhs, const ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command_id == rhs.command_id &&
    lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator1> & lhs, const ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marvelmind_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cf2339348c2fef8359cd1466b495728";
  }

  static const char* value(const ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cf2339348c2fef8ULL;
  static const uint64_t static_value2 = 0x359cd1466b495728ULL;
};

template<class ContainerAllocator>
struct DataType< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marvelmind_nav/MarvelmindAPIRequest";
  }

  static const char* value(const ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"int64 command_id\n"
"uint8[] request\n"
;
  }

  static const char* value(const ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command_id);
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MarvelmindAPIRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marvelmind_nav::MarvelmindAPIRequest_<ContainerAllocator>& v)
  {
    s << indent << "command_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.command_id);
    s << indent << "request[]" << std::endl;
    for (size_t i = 0; i < v.request.size(); ++i)
    {
      s << indent << "  request[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.request[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARVELMIND_NAV_MESSAGE_MARVELMINDAPIREQUEST_H
