joint1_position:
  type: position_controllers/JointPositionController
  joint: joint1

  
joint2_position:
  type: position_controllers/JointPositionController
  joint: joint2

  
joint3_position:
  type: position_controllers/JointPositionController
  joint: joint3

  
joint4_position:
  type: position_controllers/JointPositionController
  joint: joint4

gazebo_ros_control:
  pid_gains:
    joint1: {p: 100, i: 0.01, d: 10.0}
    joint2: {p: 100, i: 0.01, d: 10.0}
    joint3: {p: 100, i: 0.01, d: 10.0}
    joint4: {p: 100, i: 0.01, d: 10.0}
