; Auto-generated. Do not edit!


(cl:in-package action_tutorial-msg)


;//! \htmlinclude MazeGoal.msg.html

(cl:defclass <MazeGoal> (roslisp-msg-protocol:ros-message)
  ((turning_sequence
    :reader turning_sequence
    :initarg :turning_sequence
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass MazeGoal (<MazeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MazeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MazeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_tutorial-msg:<MazeGoal> is deprecated: use action_tutorial-msg:MazeGoal instead.")))

(cl:ensure-generic-function 'turning_sequence-val :lambda-list '(m))
(cl:defmethod turning_sequence-val ((m <MazeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_tutorial-msg:turning_sequence-val is deprecated.  Use action_tutorial-msg:turning_sequence instead.")
  (turning_sequence m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MazeGoal>) ostream)
  "Serializes a message object of type '<MazeGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'turning_sequence))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'turning_sequence))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MazeGoal>) istream)
  "Deserializes a message object of type '<MazeGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'turning_sequence) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'turning_sequence)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MazeGoal>)))
  "Returns string type for a message object of type '<MazeGoal>"
  "action_tutorial/MazeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MazeGoal)))
  "Returns string type for a message object of type 'MazeGoal"
  "action_tutorial/MazeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MazeGoal>)))
  "Returns md5sum for a message object of type '<MazeGoal>"
  "9f6bba6ab4d87ccf9a2d700e1f5065e6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MazeGoal)))
  "Returns md5sum for a message object of type 'MazeGoal"
  "9f6bba6ab4d87ccf9a2d700e1f5065e6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MazeGoal>)))
  "Returns full string definition for message of type '<MazeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32[] turning_sequence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MazeGoal)))
  "Returns full string definition for message of type 'MazeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32[] turning_sequence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MazeGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'turning_sequence) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MazeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MazeGoal
    (cl:cons ':turning_sequence (turning_sequence msg))
))
