  controller_manager:
    ns: /vuasrl_manipulation
    load_robot_description: true

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint3
    pid: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint4
    pid: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}

  
  gripper_position_controller:
    type: effort_controllers/JointPositionController
    joint: grip_joint
    pid: {p: 300.0, i: 1.0, d: 1.0, i_clamp: 0.2}
  gripper_sub_position_controller:
    type: effort_controllers/JointPositionController
    joint: grip_joint_sub
    pid: {p: 300.0, i: 1.0, d: 1.0, i_clamp: 0.2}

