// Generated by gencpp from file master_ros/demo_srv.msg
// DO NOT EDIT!


#ifndef MASTER_ROS_MESSAGE_DEMO_SRV_H
#define MASTER_ROS_MESSAGE_DEMO_SRV_H

#include <ros/service_traits.h>


#include <master_ros/demo_srvRequest.h>
#include <master_ros/demo_srvResponse.h>


namespace master_ros
{

struct demo_srv
{

typedef demo_srvRequest Request;
typedef demo_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct demo_srv
} // namespace master_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_ros::demo_srv > {
  static const char* value()
  {
    return "e21fb7853ad73d6d988d6371d4fed1e2";
  }

  static const char* value(const ::master_ros::demo_srv&) { return value(); }
};

template<>
struct DataType< ::master_ros::demo_srv > {
  static const char* value()
  {
    return "master_ros/demo_srv";
  }

  static const char* value(const ::master_ros::demo_srv&) { return value(); }
};


// service_traits::MD5Sum< ::master_ros::demo_srvRequest> should match
// service_traits::MD5Sum< ::master_ros::demo_srv >
template<>
struct MD5Sum< ::master_ros::demo_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_ros::demo_srv >::value();
  }
  static const char* value(const ::master_ros::demo_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_ros::demo_srvRequest> should match
// service_traits::DataType< ::master_ros::demo_srv >
template<>
struct DataType< ::master_ros::demo_srvRequest>
{
  static const char* value()
  {
    return DataType< ::master_ros::demo_srv >::value();
  }
  static const char* value(const ::master_ros::demo_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_ros::demo_srvResponse> should match
// service_traits::MD5Sum< ::master_ros::demo_srv >
template<>
struct MD5Sum< ::master_ros::demo_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_ros::demo_srv >::value();
  }
  static const char* value(const ::master_ros::demo_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_ros::demo_srvResponse> should match
// service_traits::DataType< ::master_ros::demo_srv >
template<>
struct DataType< ::master_ros::demo_srvResponse>
{
  static const char* value()
  {
    return DataType< ::master_ros::demo_srv >::value();
  }
  static const char* value(const ::master_ros::demo_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_ROS_MESSAGE_DEMO_SRV_H
