// Generated by gencpp from file master_ros/Demo_actionGoal.msg
// DO NOT EDIT!


#ifndef MASTER_ROS_MESSAGE_DEMO_ACTIONGOAL_H
#define MASTER_ROS_MESSAGE_DEMO_ACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master_ros
{
template <class ContainerAllocator>
struct Demo_actionGoal_
{
  typedef Demo_actionGoal_<ContainerAllocator> Type;

  Demo_actionGoal_()
    : count(0)  {
    }
  Demo_actionGoal_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::master_ros::Demo_actionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_ros::Demo_actionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct Demo_actionGoal_

typedef ::master_ros::Demo_actionGoal_<std::allocator<void> > Demo_actionGoal;

typedef boost::shared_ptr< ::master_ros::Demo_actionGoal > Demo_actionGoalPtr;
typedef boost::shared_ptr< ::master_ros::Demo_actionGoal const> Demo_actionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_ros::Demo_actionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_ros::Demo_actionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::master_ros::Demo_actionGoal_<ContainerAllocator1> & lhs, const ::master_ros::Demo_actionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::master_ros::Demo_actionGoal_<ContainerAllocator1> & lhs, const ::master_ros::Demo_actionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace master_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::master_ros::Demo_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_ros::Demo_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_ros::Demo_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_ros::Demo_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_ros::Demo_actionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_ros::Demo_actionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_ros::Demo_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602d642babe509c7c59f497c23e716a9";
  }

  static const char* value(const ::master_ros::Demo_actionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602d642babe509c7ULL;
  static const uint64_t static_value2 = 0xc59f497c23e716a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::master_ros::Demo_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_ros/Demo_actionGoal";
  }

  static const char* value(const ::master_ros::Demo_actionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_ros::Demo_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int32 count\n"
;
  }

  static const char* value(const ::master_ros::Demo_actionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_ros::Demo_actionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Demo_actionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_ros::Demo_actionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master_ros::Demo_actionGoal_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_ROS_MESSAGE_DEMO_ACTIONGOAL_H
