; Auto-generated. Do not edit!


(cl:in-package action_tutorial-msg)


;//! \htmlinclude MazeResult.msg.html

(cl:defclass <MazeResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass MazeResult (<MazeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MazeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MazeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_tutorial-msg:<MazeResult> is deprecated: use action_tutorial-msg:MazeResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <MazeResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_tutorial-msg:success-val is deprecated.  Use action_tutorial-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MazeResult>) ostream)
  "Serializes a message object of type '<MazeResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MazeResult>) istream)
  "Deserializes a message object of type '<MazeResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MazeResult>)))
  "Returns string type for a message object of type '<MazeResult>"
  "action_tutorial/MazeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MazeResult)))
  "Returns string type for a message object of type 'MazeResult"
  "action_tutorial/MazeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MazeResult>)))
  "Returns md5sum for a message object of type '<MazeResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MazeResult)))
  "Returns md5sum for a message object of type 'MazeResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MazeResult>)))
  "Returns full string definition for message of type '<MazeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MazeResult)))
  "Returns full string definition for message of type 'MazeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MazeResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MazeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MazeResult
    (cl:cons ':success (success msg))
))
