// Generated by gencpp from file hdl_graph_slam/DumpGraphRequest.msg
// DO NOT EDIT!


#ifndef HDL_GRAPH_SLAM_MESSAGE_DUMPGRAPHREQUEST_H
#define HDL_GRAPH_SLAM_MESSAGE_DUMPGRAPHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hdl_graph_slam
{
template <class ContainerAllocator>
struct DumpGraphRequest_
{
  typedef DumpGraphRequest_<ContainerAllocator> Type;

  DumpGraphRequest_()
    : destination()  {
    }
  DumpGraphRequest_(const ContainerAllocator& _alloc)
    : destination(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _destination_type;
  _destination_type destination;





  typedef boost::shared_ptr< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DumpGraphRequest_

typedef ::hdl_graph_slam::DumpGraphRequest_<std::allocator<void> > DumpGraphRequest;

typedef boost::shared_ptr< ::hdl_graph_slam::DumpGraphRequest > DumpGraphRequestPtr;
typedef boost::shared_ptr< ::hdl_graph_slam::DumpGraphRequest const> DumpGraphRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator1> & lhs, const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator2> & rhs)
{
  return lhs.destination == rhs.destination;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator1> & lhs, const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hdl_graph_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e47796db9d7d90bff30cd181ffc714b";
  }

  static const char* value(const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e47796db9d7d90bULL;
  static const uint64_t static_value2 = 0xff30cd181ffc714bULL;
};

template<class ContainerAllocator>
struct DataType< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdl_graph_slam/DumpGraphRequest";
  }

  static const char* value(const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"string destination\n"
;
  }

  static const char* value(const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DumpGraphRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator>& v)
  {
    s << indent << "destination: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.destination);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDL_GRAPH_SLAM_MESSAGE_DUMPGRAPHREQUEST_H
