// Generated by gencpp from file hdl_graph_slam/FloorCoeffs.msg
// DO NOT EDIT!


#ifndef HDL_GRAPH_SLAM_MESSAGE_FLOORCOEFFS_H
#define HDL_GRAPH_SLAM_MESSAGE_FLOORCOEFFS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hdl_graph_slam
{
template <class ContainerAllocator>
struct FloorCoeffs_
{
  typedef FloorCoeffs_<ContainerAllocator> Type;

  FloorCoeffs_()
    : header()
    , coeffs()  {
    }
  FloorCoeffs_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , coeffs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _coeffs_type;
  _coeffs_type coeffs;





  typedef boost::shared_ptr< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> const> ConstPtr;

}; // struct FloorCoeffs_

typedef ::hdl_graph_slam::FloorCoeffs_<std::allocator<void> > FloorCoeffs;

typedef boost::shared_ptr< ::hdl_graph_slam::FloorCoeffs > FloorCoeffsPtr;
typedef boost::shared_ptr< ::hdl_graph_slam::FloorCoeffs const> FloorCoeffsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator1> & lhs, const ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.coeffs == rhs.coeffs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator1> & lhs, const ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hdl_graph_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0861e5afa0bb6c1fd931e1b78404b45";
  }

  static const char* value(const ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0861e5afa0bb6c1ULL;
  static const uint64_t static_value2 = 0xfd931e1b78404b45ULL;
};

template<class ContainerAllocator>
struct DataType< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdl_graph_slam/FloorCoeffs";
  }

  static const char* value(const ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float32[] coeffs\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.coeffs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FloorCoeffs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdl_graph_slam::FloorCoeffs_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "coeffs[]" << std::endl;
    for (size_t i = 0; i < v.coeffs.size(); ++i)
    {
      s << indent << "  coeffs[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coeffs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDL_GRAPH_SLAM_MESSAGE_FLOORCOEFFS_H
