// Generated by gencpp from file hdl_graph_slam/LoadGraphRequest.msg
// DO NOT EDIT!


#ifndef HDL_GRAPH_SLAM_MESSAGE_LOADGRAPHREQUEST_H
#define HDL_GRAPH_SLAM_MESSAGE_LOADGRAPHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hdl_graph_slam
{
template <class ContainerAllocator>
struct LoadGraphRequest_
{
  typedef LoadGraphRequest_<ContainerAllocator> Type;

  LoadGraphRequest_()
    : path()  {
    }
  LoadGraphRequest_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadGraphRequest_

typedef ::hdl_graph_slam::LoadGraphRequest_<std::allocator<void> > LoadGraphRequest;

typedef boost::shared_ptr< ::hdl_graph_slam::LoadGraphRequest > LoadGraphRequestPtr;
typedef boost::shared_ptr< ::hdl_graph_slam::LoadGraphRequest const> LoadGraphRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator1> & lhs, const ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator1> & lhs, const ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hdl_graph_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d00cd540af97efeULL;
  static const uint64_t static_value2 = 0xb6b1589112fab63eULL;
};

template<class ContainerAllocator>
struct DataType< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdl_graph_slam/LoadGraphRequest";
  }

  static const char* value(const ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"string path\n"
;
  }

  static const char* value(const ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadGraphRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdl_graph_slam::LoadGraphRequest_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDL_GRAPH_SLAM_MESSAGE_LOADGRAPHREQUEST_H
