// Auto-generated. Do not edit!

// (in-package action_tutorial.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MazeGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.turning_sequence = null;
    }
    else {
      if (initObj.hasOwnProperty('turning_sequence')) {
        this.turning_sequence = initObj.turning_sequence
      }
      else {
        this.turning_sequence = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MazeGoal
    // Serialize message field [turning_sequence]
    bufferOffset = _arraySerializer.int32(obj.turning_sequence, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MazeGoal
    let len;
    let data = new MazeGoal(null);
    // Deserialize message field [turning_sequence]
    data.turning_sequence = _arrayDeserializer.int32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.turning_sequence.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'action_tutorial/MazeGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9f6bba6ab4d87ccf9a2d700e1f5065e6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32[] turning_sequence
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MazeGoal(null);
    if (msg.turning_sequence !== undefined) {
      resolved.turning_sequence = msg.turning_sequence;
    }
    else {
      resolved.turning_sequence = []
    }

    return resolved;
    }
};

module.exports = MazeGoal;
